apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    path: apps
    repoURL: https://github.com/kjubybot/p2p-devops-test.git
    targetRevision: master
    plugin:
      name: cue
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
